name: SS-classification-01
data:
  path: ./data/imgs/
  batch_size: 32
  shuffle: true
model:
  type: FeedForwardNN
  model_config:
    device: cpu
    dropout_rate: 0.2
    layer_dims:
      - 65536
      - 4096
      - 1024
      - 64
      - 4
train:
  save_model: false
  out_path: ./logs/{date}/{now}__{name}/
  batch_size: 32
  n_epochs: 30
  batches_per_evaluation: 1

  loss: CrossEntropyLoss
  loss_config:
    {}

  optimizer: Adam
  optimizer_config:
    lr: 0.001
  
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_config:
    factor: 0.1
    patience: 2
    verbose: true
  
  early_stopping_patience: 4

  max_grad_norm: 2. 
  grad_norm_type: 2
log:
  stdout: true
  file: true
  log_config: true
  logger_config:
    verbose: true
evaluation:
  train_metrics:
    - name: CrossEntropyLoss
      perc: 1
    - name: Accuracy
      perc: 1
  valid_metrics:
    - name: CrossEntropyLoss
    - name: Accuracy
  writers:
    - LogWritter
    - MLflowWriter
    # - NumpyWriter
    # - TensorboardWriter
