name: Experiment-name
data:
  path: ./data/
  batch_size: 4
  shuffle: true
model:
  type: ConvNet
  model_config:
    device: cpu
    dropout_rate: 0.1
    layer_dims:
      - 1
      - 32
      - 64
      - 128
      - 256
      - 4
train:
  save_model: true
  out_path: ./logs/{date}/{now}__{name}/
  batch_size: 4
  n_epochs: 10
  batches_per_evaluation: 10

  loss: CrossEntropyLoss
  loss_config:
    {}

  optimizer: Adam
  optimizer_config:
    lr: 0.01
  
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_config:
    factor: 0.1
    patience: 4
    # verbose: true
  
  early_stopping_patience: 10

  max_grad_norm: 2. 
  grad_norm_type: 2
log:
  stdout: true
  file: true
  log_config: true
  logger_config:
    verbose: true
evaluation:
  train_metrics:
    - name: CrossEntropyLoss
      perc: 0.5
  valid_metrics:
    - name: CrossEntropyLoss
  writers:
    - LogWritter
    - NumpyWriter
    - TensorboardWriter

