name: TransferLearningExperiment
data:
  path: ./data/
  batch_size: 16
  shuffle: true
model:
  type: TL_ResNet
  model_config:
    device: cpu
    dropout_rate: 0.1
    num_classes: 4
train:
  save_model: true
  out_path: ./logs/{date}/{now}__{name}/
  batch_size: 16
  n_epochs: 10
  batches_per_evaluation: 4

  loss: CrossEntropyLoss
  loss_config:
    {}

  optimizer: Adam
  optimizer_config:
    lr: 0.001
  
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_config:
    factor: 0.1
    patience: 4
    # verbose: true
  
  early_stopping_patience: 10

  max_grad_norm: 2. 
  grad_norm_type: 2
log:
  stdout: true
  file: true
  log_config: true
  logger_config:
    verbose: true
evaluation:
  train_metrics:
    - name: CrossEntropyLoss
      perc: 0.5
  valid_metrics:
    - name: CrossEntropyLoss
  writers:
    - LogWritter
    - NumpyWriter
    - TensorboardWriter
